services:
  - type: web
    name: medical-chatbot
    env: python
    runtime: python-3.12
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
