services:
  - type: web
    name: medical-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
